{
 "title": "Hammerspace File Mobility",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_exporter_duration,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_exporter_duration{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "File Movement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mobility jobs completed success vs fail / sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(msm_type, msm_pretty) (rate(hammerspace_mobility_jobs_completed{instance=~\"$node\", job=~\"$job\", ret_name=\"MSM_JS_COMPLETED\"}[$__rate_interval]))",
     "legendFormat": "Success {{msm_pretty}}"
    },
    {
     "expr": "sum by(msm_type, msm_pretty) (rate(hammerspace_mobility_jobs_completed{instance=~\"$node\", job=~\"$job\", ret_name!=\"MSM_JS_COMPLETED\"}[$__rate_interval]))",
     "legendFormat": "Failed {{msm_pretty}}"
    }
   ]
  },
  {
   "title": "Mobility jobs failed / sec by return code",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_mobility_jobs_completed{instance=~\"$node\",job=~\"$job\",ret_name!=\"MSM_JS_COMPLETED\",ret_name!=\"MSM_JS_PENDING\"}[$__rate_interval])) by (msm_type, msm_pretty, ret_name) != 0",
     "legendFormat": "Failed {{msm_pretty}} - {{ret_name}}"
    }
   ]
  },
  {
   "title": "Mobility jobs attempted / sec",
   "type": "timeseries",
   "description": "Mobility jobs where an attempt is made.  ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (msm,msm_pretty)",
     "legendFormat": "{{msm_pretty}}"
    }
   ]
  },
  {
   "title": "Files queued for mobility / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_actuary_queued_for_mobility_files{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) != 0",
     "legendFormat": "files queued"
    },
    {
     "expr": "rate(hammerspace_actuary_queued_for_mobility_files{instance=~\"$node\",job=~\"$job\"}[15m]) != 0",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "Mobility jobs at time of sample",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hammerspace_mobility_actively_moving_files{instance=~\"$node\",job=~\"$job\"} != 0",
     "legendFormat": "Live {{status}}"
    }
   ]
  },
  {
   "title": "Active/Queued mobility jobs by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hammerspace_mobility_actively_moving_files_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Active (not queued) mobility jobs by size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hammerspace_mobility_actively_moving_files_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Files for mobility dropped by actuary / sec by reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_actuary_commit_drops{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "File Movement Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Actuary runs and convergence",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(hammerspace_actuary_non_convergence_events{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) != 0",
     "legendFormat": "Non-Convergence Events"
    },
    {
     "expr": "delta(hammerspace_actuary_cycles{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Run Cycles"
    }
   ]
  },
  {
   "title": "Actuary Iterations per cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hammerspace_actuary_iterations_per_cycle{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Actuary compute time per cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "hammerspace_actuary_nanoseconds_per_cycle{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  { "title": "Alignment Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "File alignment checks / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_grading_files_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Files checked for allignment"
    },
    {
     "expr": "rate(hammerspace_grading_misaligned_files_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Misalligned files found"
    },
    {
     "expr": "rate(hammerspace_grading_files_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Files checked for alignment 15 min avg"
    },
    {
     "expr": "rate(hammerspace_grading_misaligned_files_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Misalligned files found 15min avg"
    }
   ]
  },
  {
   "title": "File alignment checks by producer / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_grading_files_producer_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{producer}}"
    }
   ]
  },
  { "title": "Alignment Analysis Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Grader books insertions / evictions rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_grading_books_insertion_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Insertions"
    },
    {
     "expr": "-1*rate(hammerspace_grading_books_eviction_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Evictions"
    },
    {
     "expr": "rate(hammerspace_grading_books_insertion_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Insertions 15m avg"
    },
    {
     "expr": "-1*rate(hammerspace_grading_books_eviction_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Evictions 15m avg"
    }
   ]
  },
  {
   "title": "Grading time per file/object",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "hammerspace_grading_time_nanoseconds_per_cycle{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Placement tests per file graded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hammerspace_grading_alternatives_per_file{instance=~\"$node\",job=~\"$job\"}  ",
     "legendFormat": "{{stat}}/file"
    }
   ]
  },
  {
   "title": "Grader Aborts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_grading_aborted_count{instance=~\"$node\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "RPC counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPCs completed / sec, success vs fail",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_dme_rpc_extended_count{instance=~\"$node\",job=~\"$job\",status=\"success\"}[$__rate_interval])) by (rpc)",
       "legendFormat": "Success {{rpc}}"
      }
     ]
    },
    {
     "title": "RPC run time p99 in msec",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hammerspace_dme_rpc_extended_timing{instance=~\"$node\",job=~\"$job\",stat=\"p99\"} / 1000 / 1000",
       "legendFormat": "{{rpc}}"
      }
     ]
    },
    {
     "title": "Old style RPC counters, attempt rpc / sec only",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_dme_rpc_attempted_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (rpc)",
       "legendFormat": "{{rpc}}"
      }
     ]
    }
   ]
  },
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Initial placement cache update run time p99",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hammerspace_dme_envoy_update_timing{instance=~\"$node\",job=~\"$job\",stat=\"p99\"}",
     "legendFormat": "{{update_type}}"
    }
   ]
  },
  {
   "title": "Initial placement cache updates by type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(hammerspace_dme_envoy_update_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{update_type}}"
    }
   ]
  },
  {
   "title": "Testing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "panels": [
    {
     "title": "% CPU Utilization for key services",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_services_cg_cpu_ns{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])/10000000) by (service)",
       "legendFormat": "{{producer}}"
      }
     ]
    },
    {
     "title": "Resident RAM usage for key services",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(hammerspace_services_cg_mem_usage{instance=~\"$node\",job=~\"$job\",type=\"resident_bytes\"}) by (service)\n\n",
       "legendFormat": "{{producer}}"
      }
     ]
    },
    {
     "title": "Swap usage for key services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(hammerspace_services_cg_mem_usage{instance=~\"$node\",job=~\"$job\",type=\"swap_bytes\"}) by (service)\n\n",
       "legendFormat": "{{producer}}"
      }
     ]
    },
    {
     "title": "Dirty IO memory for key services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(hammerspace_services_cg_mem_dirty_io{instance=~\"$node\",job=~\"$job\"}) by (service)\n\n",
       "legendFormat": "{{producer}}"
      }
     ]
    },
    {
     "title": "Bandwidth against metadata device from key services",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_services_cg_io_bytes{instance=~\"$node\",job=~\"$job\",type=\"Read\",dev=\"metadata\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Read"
      },
      {
       "expr": "sum(rate(hammerspace_services_cg_io_bytes{instance=~\"$node\",job=~\"$job\",type=\"Write\",dev=\"metadata\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Write"
      }
     ]
    },
    {
     "title": "Bandwidth against boot device from key services",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_services_cg_io_bytes{instance=~\"$node\",job=~\"$job\",type=\"Read\",dev=\"boot\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Read"
      },
      {
       "expr": "sum(rate(hammerspace_services_cg_io_bytes{instance=~\"$node\",job=~\"$job\",type=\"Write\",dev=\"boot\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Write"
      }
     ]
    },
    {
     "title": "IOs against metadata device from key services",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_services_cg_io{instance=~\"$node\",job=~\"$job\",type=\"Read\",dev=\"metadata\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Read"
      },
      {
       "expr": "sum(rate(hammerspace_services_cg_io{instance=~\"$node\",job=~\"$job\",type=\"Write\",dev=\"metadata\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Write"
      }
     ]
    },
    {
     "title": "IOs against boot device from key services",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_services_cg_io{instance=~\"$node\",job=~\"$job\",type=\"Read\",dev=\"boot\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Read"
      },
      {
       "expr": "sum(rate(hammerspace_services_cg_io{instance=~\"$node\",job=~\"$job\",type=\"Write\",dev=\"boot\"}[$__rate_interval])) by (service)\n\n",
       "legendFormat": "{{service}} Write"
      }
     ]
    }
   ]
  },
  { "title": "Object Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Key Checks/second by OSV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(osv) (rate(hammerspace_cgc_total_keys_inspected_count{instance=~\"$node\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{osv}}"
    }
   ]
  },
  {
   "title": "Capacity freed/second by OSV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(osv) (rate(hammerspace_cgc_total_bytes_freed_count{instance=~\"$node\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{osv}}"
    }
   ]
  },
  {
   "title": "Active CGC session status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(changes(hammerspace_cgc_sessions_completed_count{instance=~\"$node\", job=~\"$job\"}[1m])) != 0",
     "legendFormat": "Completed {{osv}}"
    },
    {
     "expr": "(changes(hammerspace_cgc_sessions_failed_count{instance=~\"$node\", job=~\"$job\"}[1m])) != 0",
     "legendFormat": "Failed {{osv}}"
    },
    {
     "expr": "sum by (osv) (hammerspace_cgc_session_percent_done{instance=~\"$node\", job=~\"$job\"}/100)",
     "legendFormat": "Running % {{osv}}"
    },
    {
     "expr": "(changes(hammerspace_cgc_sessions_aborted_count{instance=~\"$node\", job=~\"$job\"}[1m])) != 0",
     "legendFormat": "Stopped Early {{osv}}"
    }
   ]
  },
  {
   "title": "Active GC Session status code counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(osv) (hammerspace_cgc_sessions_in_progress_count{instance=~\"$node\", job=~\"$job\"}) != 0",
     "legendFormat": "running {{osv}}"
    },
    {
     "expr": "sum by(osv) (hammerspace_cgc_sessions_aborting_count{instance=~\"$node\", job=~\"$job\"}) != 0",
     "legendFormat": "running {{osv}} - stopping"
    },
    {
     "expr": "sum by(osv) (hammerspace_cgc_sessions_failing_count{instance=~\"$node\", job=~\"$job\"}) != 0",
     "legendFormat": "running {{osv}} - failing"
    }
   ]
  },
  {
   "title": "Time since last completed CGC, all sites",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - hammerspace_cgc_sessions_last_completed_timestamp{job=~\"$job\"}",
     "legendFormat": "{{instance}} {{osv}}"
    }
   ]
  }
 ]
}