{
 "title": "Hammerspace Protocol Stats",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_exporter_duration,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_exporter_duration{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read/Write metadata ops / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_metadata_ops{instance=~\"$node\",job=~\"$job\",type=~\"read\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "irate(hammerspace_protod_metadata_ops{instance=~\"$node\",job=~\"$job\",type=~\"write\"}[1m])*-1",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Compound ops / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_compound_ops{instance=~\"$node\",job=~\"$job\",type=~\"success\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "irate(hammerspace_protod_compound_ops{instance=~\"$node\",job=~\"$job\",type=~\"error\"}[1m])*-1",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "File creation & deletion / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_file_create_ops{instance=~\"$node\",job=~\"$job\"}[1m])",
     "legendFormat": "Create"
    },
    {
     "expr": "irate(hammerspace_protod_file_delete_ops{instance=~\"$node\",job=~\"$job\"}[1m])*-1",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "delegation stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_delegations{instance=~\"$node\",job=~\"$job\",type=\"granted\"}[1m])",
     "legendFormat": "Granted / sec"
    },
    {
     "expr": "irate(hammerspace_protod_delegations{instance=~\"$node\",job=~\"$job\",type=\"denied\"}[1m])*-1",
     "legendFormat": "Denied / sec"
    },
    {
     "expr": "hammerspace_protod_delegations{instance=~\"$node\",job=~\"$job\",type=\"active_delegations\"}",
     "legendFormat": "Active Delegations"
    }
   ]
  },
  {
   "title": "file open stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_opens{instance=~\"$node\",job=~\"$job\",type=\"granted\"}[1m])",
     "legendFormat": "Opens  / sec"
    },
    {
     "expr": "irate(hammerspace_protod_opens{instance=~\"$node\",job=~\"$job\",type=\"denied\"}[1m])*-1",
     "legendFormat": "Opens Denied / sec"
    },
    {
     "expr": "hammerspace_protod_opens{instance=~\"$node\",job=~\"$job\",type=\"currently_open\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "Delay tracking leading indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Delay tracking of shareid-inode with still active ops (shares view)",
   "type": "timeseries",
   "description": "This can be blank, it is not a bug\nUsually if you see ongoing delay tracking issues check with PDFS",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(share_id, inode) (rate(hammerspace_nfs_protocol_op_delay_tracking{instance=~\"$node\", job=~\"$job\"}[$__rate_interval])) != 0",
     "legendFormat": "{{share_id}}-{{inode}}"
    }
   ]
  },
  {
   "title": "Delay tracking of active ops by op",
   "type": "timeseries",
   "description": "This can be blank, it is not a bug\nUsually if you see ongoing delay tracking issues check with PDFS",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hammerspace_nfs_protocol_op_delay_tracking{instance=~\"$node\",job=~\"$job\"}) by (op_name) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Layout error delay tracking of shareid-inode with still active ops (shares view)",
   "type": "timeseries",
   "description": "This can be blank, it is not a bug\nUsually if you see ongoing delay tracking issues check with PDFS",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_layout_errors_delay_tracking{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (share_id, inode) != 0",
     "legendFormat": "{{share_id}}-{{inode}}"
    }
   ]
  },
  {
   "title": "Layout error delay by volume (volumes view)",
   "type": "timeseries",
   "description": "This can be blank, it is not a bug\nUsually if you see ongoing delay tracking issues check with PDFS",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_layout_errors_delay_tracking{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (volume, volume_id) != 0",
     "legendFormat": "{{volume}} ({{volume_id}})"
    }
   ]
  },
  {
   "title": "Layout Errors Overview (reported by clients)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Layout errors/sec of all types reported by client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_layout_errors_by_client{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (client_ip,client_id) != 0",
     "legendFormat": "{{client_ip}} ({{client_id}})"
    }
   ]
  },
  {
   "title": "Layout errors/sec reported against each volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_layout_errors_by_volume{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (volume,volume_id) != 0",
     "legendFormat": "{{volume}} ({{volume_id}})"
    }
   ]
  },
  {
   "title": "Layout errors/sec by type (clients view)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_layout_errors_by_client{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (err)",
     "legendFormat": "{{err}}"
    }
   ]
  },
  {
   "title": "Layout errors/sec by type (volumes view)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_layout_errors_by_volume{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (err)",
     "legendFormat": "{{err}}"
    }
   ]
  },
  {
   "title": "Server Errors Overview (reported by server)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "Server errors/sec of all types reported against client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_server_errors_by_client{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (client_ip,client_id) != 0",
     "legendFormat": "{{client_ip}} ({{client_id}})"
    }
   ]
  },
  {
   "title": "Server errors/sec of all types reported against share",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_server_errors_by_share{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (share_id,share)",
     "legendFormat": "{{share}} ({{share_id}})"
    }
   ]
  },
  {
   "title": "Server errors by type (client view)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_server_errors_by_client{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (err)",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Server errors by type (share view)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_nfs_protocol_server_errors_by_share{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (err)",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Individual Op Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS ops / second at protocol layer",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "NFS ops / second from protocol passed to filesystem",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "NFS ops / second from protocol against storage volumes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_to_storage_volumes{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "NFS ops / second from shadow files",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"shadow\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Individual op counts raw",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS ops at protocol layer",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "idelta(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "NFS ops from protocol passed to filesystem",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "idelta(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "NFS ops from protocol against storage volumes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "idelta(hammerspace_nfs_protocol_ops_to_storage_volumes{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "NFS ops from shadow files",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "idelta(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"shadow\"}[1m])",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Walltime per Individual Op at each layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Milliseconds / op at protocol layer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Milliseconds / op at filesystem layer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m]) / irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Milliseconds / op sent to storage volumes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_to_storage_volumes_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / irate(hammerspace_nfs_protocol_ops_to_storage_volumes{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Walltime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Milliseconds by op type at protocol layer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Total Milliseconds by op type at filesystem layer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Total Milliseconds by op type sent to storage volumes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_to_storage_volumes_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    }
   ]
  }
 ]
}