{
 "title": "Hammerspace Replication",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_exporter_duration,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_exporter_duration{node_type=\"clusterip\"},instance)"
    }
   },
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(hammerspace_filesystem_ops,share)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metadata Replication - Up-to-date monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Worst Share Send Seconds Behind by Sender",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(hammerspace_filesystem_replication_send_behind{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}) by (from_site)",
     "legendFormat": "{{from_site}}"
    }
   ]
  },
  {
   "title": "Worst Share Send Seconds Behind by Reciever",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(hammerspace_filesystem_replication_send_behind{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}) by (to_site)",
     "legendFormat": "{{to_site}}"
    }
   ]
  },
  {
   "title": "Aggragate seconds behind by site pair",
   "type": "timeseries",
   "description": "Ignores any share that is less than 120 seconds behind",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(from_site, to_site) (hammerspace_filesystem_replication_send_behind{instance=~\"$node\", job=~\"$job\", share=~\"$share\"} > 120)",
     "legendFormat": "{{from_site}} -> {{to_site}}"
    }
   ]
  },
  {
   "title": "Number of receiving shares more than 10 minutes behind (stacked)",
   "type": "timeseries",
   "description": "Bouncing around zero is good, consistent positive is bad.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(to_site) (hammerspace_filesystem_replication_send_behind{instance=~\"$node\", job=~\"$job\", share=~\"$share\"} > 600)",
     "legendFormat": "-> {{to_site}}"
    }
   ]
  },
  {
   "title": "Metadata Replication - Aggregate activity stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Rate of replication send activity -- all sites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",share=~\"$share\",status=\"sent\"}[$__rate_interval]))",
     "legendFormat": "Sends"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",share=~\"$share\",status=\"sent\"}[15m]))",
     "legendFormat": "Sends 15 min avg"
    }
   ]
  },
  {
   "title": "Successful SNAP sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"ok\",share=~\"$share\",type=\"snap\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Sends Success {{instance}}"
    }
   ]
  },
  {
   "title": "Failed SNAP sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"fail\",share=~\"$share\",type=\"snap\"}[$__rate_interval])) by (instance) *-1",
     "legendFormat": "Sends Failed {{instance}}"
    }
   ]
  },
  {
   "title": "Successful INODE sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"ok\",share=~\"$share\",type=\"inode\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Sends Success {{instance}}"
    }
   ]
  },
  {
   "title": "Failed INODE sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"fail\",share=~\"$share\",type=\"inode\"}[$__rate_interval])) by (instance) *-1",
     "legendFormat": "Sends Failed {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of replication sends by type and success -- all sites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"snap\",status=\"ok\",share=~\"$share\"}[$__rate_interval]))",
     "legendFormat": "SNAP Sends Success"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"snap\",status=\"fail\",share=~\"$share\"}[$__rate_interval]))*-1",
     "legendFormat": "SNAP Sends Failed"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"inode\",status=\"ok\",share=~\"$share\"}[$__rate_interval]))",
     "legendFormat": "INODE Sends Success"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"inode\",status=\"fail\",share=~\"$share\"}[$__rate_interval]))*-1",
     "legendFormat": "INODE Sends Failed"
    }
   ]
  },
  {
   "title": "Replication diff starts by share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"snap\",status=\"sent\"}[$__rate_interval]) > 0",
     "legendFormat": "{{share}} {{instance}} SNAP sends"
    }
   ]
  },
  {
   "title": "% of merge attempts that are non-zero -- per site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n(sum(increase(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\",ret_num!=\"0\"}[$__rate_interval])) by (instance))\n /\n(sum(increase(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\"}[$__rate_interval])) by (instance))\n)*100",
     "legendFormat": "% non-zero {{instance}}"
    }
   ]
  },
  {
   "title": "Data Replication - Aggregate activity counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "on-demand files - data -  in last 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\",msm_pretty=~\".*download.*demand.*\"}[10m])) by (instance)",
     "legendFormat": "download (remote) -- {{instance}}"
    },
    {
     "expr": "sum(increase(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\",msm_pretty=~\".*upload.*demand.*\"}[10m])) by (instance) != 0",
     "legendFormat": "upload (remote) -- {{instance}}"
    },
    {
     "expr": "0",
     "legendFormat": "download (local) (counter not yet implemented)"
    }
   ]
  },
  {
   "title": "on-demand files - hash only -  in last 10 minutes",
   "type": "timeseries",
   "description": "Cross site requests for a hash",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(increase(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\",msm_pretty=~\".*request.*demand.*\"}[10m])) by (instance) - sum(increase(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\",msm_pretty=~\".*download.*demand.*\"}[10m])) by (instance)) != 0 ",
     "legendFormat": "download {{instance}}"
    },
    {
     "expr": "(sum(increase(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\",msm_pretty=~\".*provide.*demand.*\"}[10m])) by (instance) - sum(increase(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\",msm_pretty=~\".*upload.*demand.*\"}[10m])) by (instance)) != 0",
     "legendFormat": "upload {{instance}}"
    }
   ]
  },
  {
   "title": "NAS used by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/vols3/.*\"} - node_filesystem_avail_bytes{mountpoint=~\"/mnt/vols3/.*\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "NAS free by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(cluster) (node_filesystem_avail_bytes{mountpoint=~\"/mnt/vols3/.*\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "NAS % used by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-sum(node_filesystem_avail_bytes{mountpoint=~\"/mnt/vols3/.*\"}) by (cluster) / sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/vols3/.*\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Metadata Replication - Per site activity stats - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "repeat": "node"
  },
  {
   "title": "Replication merge attempts by return code -- $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\"}[$__rate_interval])) by (ret_name, ret_num)",
     "legendFormat": "merges {{ret_name}} ({{ret_num}})"
    }
   ]
  },
  {
   "title": "Replication diffs by return code -- $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replicate_diff\"}[$__rate_interval])) by (ret_name, ret_num)",
     "legendFormat": "diff {{ret_name}} ({{ret_num}})"
    }
   ]
  },
  {
   "title": "Replication op average time -- $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\"}[$__rate_interval])+rate(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\"}[$__rate_interval]))",
     "legendFormat": "merge"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replicate_diff\"}[$__rate_interval])+rate(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replicate_diff\"}[$__rate_interval]))",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}